jQuery.extend(Drupal.settings, {
    "basePath": "..\/..\/common\/",
    "pathPrefix": "",
    "ajaxPageState": {
        "theme": "multicommander",
        "theme_token": "nlTM4VV0NmwTs5kTgnsBYJHfgSsRVRk8y3yQbfoRPj4",
        "js": {
            "sites/all/themes/bootstrap/js/bootstrap.js": 1,
            "sites/all/modules/respondjs/lib/respond.min.js": 1,
            "sites/all/modules/jquery_update/replace/jquery/1.10/jquery.min.js": 1,
            "misc/jquery.once.js": 1,
            "misc/drupal.js": 1,
            "sites/all/modules/lightbox2/js/lightbox.js": 1,
            "sites/all/modules/google_analytics/googleanalytics.js": 1,
            "0": 1,
            "sites/all/themes/multicommander/bootstrap/js/affix.js": 1,
            "sites/all/themes/multicommander/bootstrap/js/alert.js": 1,
            "sites/all/themes/multicommander/bootstrap/js/button.js": 1,
            "sites/all/themes/multicommander/bootstrap/js/carousel.js": 1,
            "sites/all/themes/multicommander/bootstrap/js/collapse.js": 1,
            "sites/all/themes/multicommander/bootstrap/js/dropdown.js": 1,
            "sites/all/themes/multicommander/bootstrap/js/modal.js": 1,
            "sites/all/themes/multicommander/bootstrap/js/tooltip.js": 1,
            "sites/all/themes/multicommander/bootstrap/js/popover.js": 1,
            "sites/all/themes/multicommander/bootstrap/js/scrollspy.js": 1,
            "sites/all/themes/multicommander/bootstrap/js/tab.js": 1,
            "sites/all/themes/multicommander/bootstrap/js/transition.js": 1,
            "sites/all/themes/multicommander/js/responsiveslides.min.js": 1,
            "sites/all/themes/multicommander/js/multicommander.js": 1,
            "sites/all/themes/multicommander/js/jquery-migrate-1.2.1.js": 1
        },
        "css": {
            "modules/system/system.base.css": 1,
            "sites/all/modules/date/date_api/date.css": 1,
            "modules/field/theme/field.css": 1,
            "modules/node/node.css": 1,
            "sites/all/modules/views/css/views.css": 1,
            "sites/all/modules/ckeditor/css/ckeditor.css": 1,
            "sites/all/modules/ctools/css/ctools.css": 1,
            "sites/all/modules/lightbox2/css/lightbox.css": 1,
            "sites/all/themes/multicommander/css/responsiveslides.css": 1,
            "sites/all/themes/multicommander/css/bootstrap.css": 1,
            "sites/all/themes/multicommander/css/style.css": 1,
            "sites/all/themes/multicommander/css/responsive-phablet.css": 1,
            "sites/all/themes/multicommander/css/responsive-tablet.css": 1,
            "sites/all/themes/multicommander/css/responsive-desktop.css": 1
        }
    },
    "lightbox2": {
        "rtl": 0,
        "file_path": "\/(\\w\\w\/)public:\/",
        "default_image": "..\/..\/common\/sites\/all\/modules\/lightbox2\/images\/brokenimage.jpg",
        "border_size": 10,
        "font_color": "000",
        "box_color": "fff",
        "top_position": "",
        "overlay_opacity": "0.8",
        "overlay_color": "000",
        "disable_close_click": 1,
        "resize_sequence": 0,
        "resize_speed": 400,
        "fade_in_speed": 400,
        "slide_down_speed": 600,
        "use_alt_layout": 0,
        "disable_resize": 0,
        "disable_zoom": 0,
        "force_show_nav": 0,
        "show_caption": 1,
        "loop_items": 0,
        "node_link_text": "View Image Details",
        "node_link_target": 0,
        "image_count": "Image !current of !total",
        "video_count": "Video !current of !total",
        "page_count": "Page !current of !total",
        "lite_press_x_close": "press \u003Ca href=\u0022#\u0022 onclick=\u0022hideLightbox(); return FALSE;\u0022\u003E\u003Ckbd\u003Ex\u003C\/kbd\u003E\u003C\/a\u003E to close",
        "download_link_text": "",
        "enable_login": false,
        "enable_contact": false,
        "keys_close": "c x 27",
        "keys_previous": "p 37",
        "keys_next": "n 39",
        "keys_zoom": "z",
        "keys_play_pause": "32",
        "display_image_size": "original",
        "image_node_sizes": "()",
        "trigger_lightbox_classes": "",
        "trigger_lightbox_group_classes": "",
        "trigger_slideshow_classes": "",
        "trigger_lightframe_classes": "",
        "trigger_lightframe_group_classes": "",
        "custom_class_handler": 0,
        "custom_trigger_classes": "",
        "disable_for_gallery_lists": true,
        "disable_for_acidfree_gallery_lists": true,
        "enable_acidfree_videos": true,
        "slideshow_interval": 5000,
        "slideshow_automatic_start": 1,
        "slideshow_automatic_exit": 1,
        "show_play_pause": 1,
        "pause_on_next_click": 0,
        "pause_on_previous_click": 1,
        "loop_slides": 0,
        "iframe_width": 600,
        "iframe_height": 400,
        "iframe_border": 1,
        "enable_video": 0
    },
    "googleanalytics": {
        "trackOutbound": 1,
        "trackMailto": 1,
        "trackDownload": 1,
        "trackDownloadExtensions": "7z|aac|arc|arj|asf|asx|avi|bin|csv|doc(x|m)?|dot(x|m)?|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|msi|msp|pdf|phps|png|ppt(x|m)?|pot(x|m)?|pps(x|m)?|ppam|sld(x|m)?|thmx|qtm?|ra(m|r)?|sea|sit|tar|tgz|torrent|txt|wav|wma|wmv|wpd|xls(x|m|b)?|xlt(x|m)|xlam|xml|z|zip"
    },
    "bootstrap": {
        "anchorsFix": 0,
        "anchorsSmoothScrolling": 1,
        "formHasError": 1,
        "popoverEnabled": 0,
        "popoverOptions": {
            "animation": 1,
            "html": 0,
            "placement": "right",
            "selector": "",
            "trigger": "click",
            "triggerAutoclose": 1,
            "title": "",
            "content": "",
            "delay": 0,
            "container": "body"
        },
        "tooltipEnabled": 1,
        "tooltipOptions": {
            "animation": 1,
            "html": 0,
            "placement": "auto left",
            "selector": "",
            "trigger": "hover focus",
            "delay": 0,
            "container": "body"
        }
    }
});